### ISSUE TITLE
Convert gene_IDs_names to toml

### ISSUE THREAD

**Issue by manulera** [manulera/genestorian_data_refinement#17]
Create a script `get_data/convert_genes2toml.py` that writes the file `data/genes.toml` from `data/gene_IDs_names.tsv`, the same way that `get_data/convert_alleles2toml.py` writes `data/alleles_pombemine.tsv`.

What the fields are is explained in [the readme](https://github.com/manulera/genestorian_data_refinement#gene-names-and-synonyms).

For a row in the file, such as:

```
SPAC1250.01	snf21	SPAC29A4.21,brg1
```

The output should be

```toml
# Note that here the gene name is doublequoted, because it contains a dot, so that toml doesn't think we 
# are specifying a subclass. You don't have to specify this in python, you can use 'SPAC1250.01' as a dictionary
# key, and it will know to format it like this for the output.
[gene."SPAC1250.01"] 
ref = "SPAC1250.01"
# "name" will be empty sometimes. Not all genes have a preferred name.
# This should be taken into account when replacing gene names
name = "snf21"
# This field will be missing sometimes (not all genes have synonyms).
synonyms = ["SPAC29A4.21", "brg1"]
```
